[versions]
agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"

navigation = "2.9.6"

hiltViewModelCompose = "1.3.0"

daggerHilt = "2.57.2"

datastore = "1.2.0"

room = "2.8.4"

json = "2.13.2"

junitJupiter = "6.0.1"

runner = "1.7.0"
rules = "1.7.0"

pagin = "3.3.6"

testCore = "1.7.0"
testCoreKtx = "1.7.0"

mockito = "5.20.0"
mockitoKotlin = "6.1.0"

timber = "5.0.1"

kotlinSerialization = "1.9.0"
pluginKotlinSerialization = "2.2.21"

apachePdfBox = "2.0.27.0"

kspVersion = "2.2.21-2.0.4"

uicomponents = "1.1.25"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

androidx-foundation = { group = "androidx.compose.foundation", name = "foundation" }

androidx-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }

androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

androidx-hilt-lifecycle-viewmodel-compose = { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel-compose", version.ref = "hiltViewModelCompose" }

androidx-datastore-preferences = { group ="androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerHilt" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-pagin = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "json" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }

androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitVersion" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "testCore" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "testCoreKtx" }

androidx-paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "pagin" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagin" }

mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

apache-pdfbox = { group = "com.tom-roush", name = "pdfbox-android", version.ref = "apachePdfBox" }

kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinSerialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }
uicomponents = { group = "com.akari", name = "uicomponents", version.ref = "uicomponents" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }

google-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "pluginKotlinSerialization" }